### ISSUE TITLE
Support input/output lists.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-bindings#22]
#21 was an initial PR that tried to add support for input/output lists. However, there are some issues:
* When the result type is an array, the generation script should not generate `Tensor(handle: ...)` calls, but `ret.map { Tensor(handle: $0) }` instead.
* Heterogeneous input/output lists need more support. They should probably be filtered initially.

**Comment by rxwei** [comment]
cc @eaplatanios @pschuh @dan-zheng

**Comment by rxwei** [comment]
@pschuh, can you elaborate the issues and propose a solution?

**Comment by pschuh** [comment]
Here are some problems:
- The mentioned ret.map { ... } problem.
- #tfop can only currently return TensorGroup if I recall correctly.
- Some tensorflow ops can return (and take) arrays heterogeneous in type.
- The common pattern ([AnyTensor], [Dtype], ...) -> (...) and ([DType], ...) -> ([AnyTensor]) Do not seem to be supported properly at all. (See saveV2 for reference).
- I haven't verified, but the length of the resulting type is sometimes determined by input parameters, but must also be completely determined by the size of the output. This correspondence is not currently captured anywhere (except a hard-coded thing in IRGen for certain special ops).

My a proposed solution is to merge: https://github.com/pschuh/swift-bindings/tree/3. This will make it easier to generate the right code here. We will need to analyze the incoming proto and generate the result-length + if it is co-varying. (analyzing fields like: type_list_attr: "dtypes"). @bgogul would know more about the status of this proposed solution.

**Comment by eaplatanios** [comment]
Given that there is no GPE now, isn't the solution implemented in [https://github.com/pschuh/swift-bindings/tree/3](https://github.com/pschuh/swift-bindings/tree/3) too inefficient? For example, adding two scalar tensors involves multiple dynamic library calls.

**Comment by eaplatanios** [comment]
In TF Scala, I was able to extract all relevant information statically, for supporting input and output tensor arrays so I cannot see why we cannot do it here. Regarding heterogeneous arrays, I believe this should be handled by allowing something like `Tensor<_>` or `Tensor<TensorFlowScalar>`, although I'm not sure if this can be done in Swift, currently.

**Comment by pschuh** [comment]
How do you think it could be more efficient? The calls I have there are the same calls that eager op dispatch compiles to when the tfops make it to IRGen to get lowered.

**Comment by eaplatanios** [comment]
Yes sorry. For eager mode I guess there is no more efficient way. Is there something preventing merging that solution currently?

**Comment by pschuh** [comment]
We currently still have GPE code executing in unit-tests that requires these to be #tfops. I think we're several weeks out from completely sorting that out. We want to maintain machinery so that we can GPE functions.

Is there a particular op that would let you be unblocked for: https://github.com/tensorflow/swift-apis/pull/70 ? I could work on special case generating a raw op for that that only works in eager mode.

**Comment by eaplatanios** [comment]
One question would be, what does it take to support array-valued op inputs and outputs in `#tfop`? Given that I support them in TF Scala, which uses graph mode, I suppose we should also be able to support them here, without sacrificing GPE support for now.

**Comment by rxwei** [comment]
Inputs can already be any array that conforms to `TensorArrayProtocol`. Outputs are trickier like @pschuh described. 

What use case is blocked by this currently?

**Comment by eaplatanios** [comment]
One example is the `Split` and the `SplitV` ops that are required for the VJP of `concatenated` when used with more than just two tensors.

**Comment by rxwei** [comment]
It’s reasonable to add ops that take homogeneous lists. Returning variable-length output lists may be problematic. IIRC, eager execution required an output count?

**Comment by eaplatanios** [comment]
In Scala, I was passing the count when constructing the ops in the graph, for graph mode, and just passing it directly for eager mode. So, the split ops for example, take the number of splits as an input attribute, if I remember correctly.

**Comment by eaplatanios** [comment]
@rxwei @pschuh Is there something we can do to support the `SplitV2` op for now? It is needed for defining gradients of the stacking and the concatenation ops.

**Comment by pschuh** [comment]
Perhaps this: https://github.com/apple/swift/pull/24096 ?

**Comment by rxwei** [comment]
Nice!

**Comment by eaplatanios** [comment]
This is great! Thanks Parker! Once this is in I can go ahead and add gradients for the new stacking and concatenation ops, as well as add an "init(unstacking:)" tensor initializer which is necessary for the RL library I'm developing.

**Comment by rxwei** [comment]
I think it can be an instance method on `Tensor`: `split(...)`.

**Comment by eaplatanios** [comment]
@pschuh We can also close this since it's handled by #26.
